# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages
# , parClasses ? import <par-classes>
, parClasses ? (import ../par-classes {})
}:

with haskellPackages;
haskellPackages.cabal.mkDerivation (self: {
  pname = "par-collections";
  version = "1.2";
  sha256 = "1111111111111111111111111111111111111111111111111111";
  src = ./.;
  buildDepends = [
    cereal deepseq mtl primitive random transformers vector
    parClasses 
  ];
  meta = {
    description = "Generic parallel combinators for data and iteration spaces";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
